name: Enviar Relatório de Mergulho

on:
  schedule:
    # Roda todos os dias às 7h da manhã (UTC)
    - cron: '0 7 * * *'
  # Permite rodar manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  enviar-relatorio:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Enviar relatório
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_DESTINATARIOS: ${{ secrets.EMAIL_DESTINATARIOS }}
      run: python mergulho_emailer.py 